### ISSUE TITLE
traducción pendiente de stringr::sentences

### ISSUE THREAD

**Issue by rivaquiroga** [cienciadedatos/datos#43]
Falta traducir los datos de `sentences`, que está contenido en `stringr`. Se utilizan en el capítulo sobre cadenas de caracteres.

**Comment by maurolepore** [comment]
I'm working on this right now

**Comment by edgararuiz-zz** [comment]
@maurolepore - I merged your PR, but forgot that we also need to translate the name of the data set itself, so instead of `sentences`, it should be something such as `oraciones`.  Also, can you remove the back-ticks from the description please? `yaml` does not seem to like them. Usage needs to be corrected, it says diamonds.  Thanks!!
