### ISSUE TITLE
problema en nombre de columna en traducción de ´babynames´

### ISSUE THREAD

**Issue by rivaquiroga** [cienciadedatos/datos#98]
¡Hola! La variable original (`n`) queda traducida como `FALSE`.

**Comment by pachadotdev** [comment]
tb pasa en fueleconomy

**Comment by pachadotdev** [comment]
# problem when calling `read_yaml()`
ping @viking
@rivaquiroga detected a problem when reading single character column names that are read as `FALSE` here: https://github.com/cienciadedatos/datos/blob/master/inst/specs/babynames.yml#L14
I also detected the same problem here: https://github.com/cienciadedatos/datos/blob/master/inst/specs/common.yml#L11
my "solution" was to put the `n` in quotes, and you can see that the problem comes from `read_yaml()` as it was used on https://github.com/cienciadedatos/datos/blob/master/R/translate.R#L3 to translate the datasets to spanish
